module Kobako
  module Catalog
    module Snippet
      class Source < Data
        KIND: String

        attr_reader name: Symbol
        attr_reader body: String

        def self.new: (name: Symbol, body: String) -> Source
                    | (Symbol name, String body) -> Source
      end
    end
  end
end
