module Kobako
  module Codec
    module Decoder
      def self.decode: [T] (String bytes) { (untyped value) -> T } -> T
                     | (String bytes) -> untyped

      private

      def self.validate_utf8!: (untyped value) -> void
    end
  end
end
