module Kobako
  module Codec
    module Decoder
      INVALID_TYPE_ERRORS: Array[Class]
      TRUNCATED_ERRORS: Array[Class]

      def self.decode: (String bytes) -> untyped

      def self.validate_utf8!: (untyped value) -> void

      def self.validate_string_utf8!: (String value) -> void

      def self.validate_pair_utf8!: (untyped key, untyped value) -> void
    end
  end
end
