module Kobako
  module Codec
    module Decoder
      INVALID_TYPE_ERRORS: Array[Class]
      TRUNCATED_ERRORS: Array[Class]

      def self.decode: (String bytes) -> untyped

      private

      def self.validate_utf8!: (untyped value) -> void
    end
  end
end
