module Kobako
  module Codec
    class Error < StandardError
    end

    class TruncatedInputError < Error
    end

    class InvalidTypeError < Error
    end

    class InvalidEncodingError < Error
    end

    class UnsupportedTypeError < Error
    end
  end
end
