module Kobako
  module Codec
    class Factory
      include Singleton
      extend Forwardable
      extend SingleForwardable

      EXT_SYMBOL: Integer
      EXT_HANDLE: Integer
      EXT_ERRENV: Integer

      def dump: (untyped value) -> String
      def load: (String bytes) -> untyped

      def self.dump: (untyped value) -> String
      def self.load: (String bytes) -> untyped

      private

      def initialize: () -> void
      def register_symbol_type: () -> void
      def pack_symbol: (Symbol symbol) -> String
      def decode_symbol: (String payload) -> Symbol
      def register_handle_type: () -> void
      def register_exception_type: () -> void
      def decode_handle: (String payload) -> Kobako::Wire::Handle
      def pack_exception: (Kobako::Wire::Exception exc) -> String
      def unpack_exception: (String payload) -> Kobako::Wire::Exception
    end
  end
end
