module Kobako
  module Codec
    class Factory
      extend SingleForwardable

      MAX_EXT_DEPTH: Integer
      FACTORY_KEY: Symbol

      def self.instance: () -> Factory

      def dump: (untyped value) -> String
      def load: (String bytes) -> untyped
      def reset_handle_tracking!: () -> void
      def saw_handle?: () -> bool
      def record_handle!: () -> void
      def within_ext_frame: [T] (singleton(Kobako::Codec::Error) over_limit) { () -> T } -> T

      def self.dump: (untyped value) -> String
      def self.load: (String bytes) -> untyped
      def self.reset_handle_tracking!: () -> void
      def self.saw_handle?: () -> bool

      private

      def initialize: () -> void
    end
  end
end
