module Kobako
  module Codec
    class Factory
      include Singleton
      extend Forwardable
      extend SingleForwardable

      EXT_SYMBOL: Integer
      EXT_HANDLE: Integer
      EXT_ERRENV: Integer

      def dump: (untyped value) -> String
      def load: (String bytes) -> untyped

      def self.dump: (untyped value) -> String
      def self.load: (String bytes) -> untyped

      private

      def initialize: () -> void
      def register_symbol: () -> void
      def pack_symbol: (Symbol symbol) -> String
      def unpack_symbol: (String payload) -> Symbol
      def register_handle: () -> void
      def register_fault: () -> void
      def unpack_handle: (String payload) -> Kobako::RPC::Handle
      def pack_fault: (Kobako::RPC::Fault fault) -> String
      def unpack_fault: (String payload) -> Kobako::RPC::Fault
    end
  end
end
