module Kobako
  module Codec
    module HandleWalk
      MSGPACK_INT_RANGE: Range[Integer]

      def self?.representable?: (untyped value) -> bool

      def self?.deep_wrap: (untyped value, Kobako::Catalog::Handles handler) -> untyped

      def self?.deep_restore: (untyped value, Kobako::Catalog::Handles handler) -> untyped

      def self?.primitive_type?: (untyped value) -> bool

      def self?.container_representable?: (untyped value) -> bool
    end
  end
end
