module Kobako
  module Codec
    module Utils
      def self?.assert_utf8!: (String string, String label) -> void

      def self?.translate_value_object_error: [T] () { () -> T } -> T
    end
  end
end
