module Kobako
  module Wire
    module Codec
      module Factory
        EXT_SYMBOL: Integer
        EXT_HANDLE: Integer
        EXT_ERRENV: Integer

        def self.instance: () -> untyped

        def self.build: () -> untyped

        def self.register_symbol_type: (untyped factory) -> untyped

        def self.pack_symbol: (Symbol symbol) -> String

        def self.decode_symbol: (String payload) -> Symbol

        def self.register_handle_type: (untyped factory) -> untyped

        def self.register_exception_type: (untyped factory) -> untyped

        def self.decode_handle: (String payload) -> Handle

        def self.pack_exception: (Exception exc) -> String

        def self.unpack_exception: (String payload) -> Exception
      end
    end
  end
end
