module Kobako
  module Transport
    module Dispatcher
      class UndefinedTargetError < StandardError
      end

      BREAK_THROW: Symbol

      META_OWNERS: Array[Module]

      GADGET_OWNERS: Array[Module]

      CALLABLE_ALLOW: Array[Symbol]

      def self?.dispatch: (String request_bytes, Kobako::Transport::_NamespaceRegistry namespaces, Kobako::Codec::_HandleTable handler, Kobako::Transport::_GuestYielder yield_to_guest) -> String

      def self?.resolve_call_args: (Kobako::Transport::Request request, Kobako::Codec::_HandleTable handler, bool carried_handle) -> [Array[untyped], Hash[Symbol, untyped]]

      def self?.encode_caught_error: (StandardError error) -> String

      def self?.invoke: (untyped target, String method, Array[untyped] args, Hash[Symbol, untyped] kwargs, ?Kobako::Transport::Yielder? yielder) -> untyped

      def self?.reject_meta_method!: (untyped target, Symbol name) -> void

      def self?.reject_unexposed!: (untyped target, Symbol name) -> void

      def self?.resolve_arg: (untyped value, Kobako::Codec::_HandleTable handler) -> untyped

      def self?.resolve_target: (String | Kobako::Handle target, Kobako::Transport::_NamespaceRegistry namespaces, Kobako::Codec::_HandleTable handler) -> untyped

      def self?.resolve_path: (String path, Kobako::Transport::_NamespaceRegistry namespaces) -> untyped

      def self?.require_live_object!: (Integer id, Kobako::Codec::_HandleTable handler) -> untyped

      def self?.encode_ok: (untyped value, Kobako::Codec::_HandleTable handler) -> String

      def self?.wrap_as_handle: (untyped value, Kobako::Codec::_HandleTable handler) -> Kobako::Handle

      def self?.encode_error: (String type, String message) -> String
    end
  end
end
