module Kobako
  module Transport
    STATUS_OK: Integer
    STATUS_ERROR: Integer

    class Request < Data
      attr_reader target: String | Kobako::Handle
      attr_reader method_name: String
      attr_reader args: Array[untyped]
      attr_reader kwargs: Hash[Symbol, untyped]
      attr_reader block_given: bool

      def self.new: (target: String | Kobako::Handle, method_name: String, ?args: Array[untyped], ?kwargs: Hash[Symbol, untyped], ?block_given: bool) -> Request

      def self.decode: (String bytes) -> Request

      def initialize: (target: String | Kobako::Handle, method_name: String, ?args: Array[untyped], ?kwargs: Hash[Symbol, untyped], ?block_given: bool) -> void

      def encode: () -> String

      def with: (?target: String | Kobako::Handle, ?method_name: String, ?args: Array[untyped], ?kwargs: Hash[Symbol, untyped], ?block_given: bool) -> Request

      def ==: (untyped other) -> bool

      def hash: () -> Integer

      private

      def validate_kwargs!: (Hash[untyped, untyped] kwargs) -> void
    end
  end
end
