module Kobako
  module Transport
    STATUS_OK: Integer
    STATUS_ERROR: Integer

    class Request
      attr_reader target: String | Kobako::Handle
      attr_reader method_name: String
      attr_reader args: Array[untyped]
      attr_reader kwargs: Hash[Symbol, untyped]
      attr_reader block_given: bool

      def initialize: (target: String | Kobako::Handle, method: String, ?args: Array[untyped], ?kwargs: Hash[Symbol, untyped], ?block_given: bool) -> void

      def with: (?target: String | Kobako::Handle, ?method: String, ?args: Array[untyped], ?kwargs: Hash[Symbol, untyped], ?block_given: bool) -> Request

      def ==: (untyped other) -> bool

      def hash: () -> Integer
    end

    def self.encode_request: (Request request) -> String

    def self.decode_request: (String bytes) -> Request
  end
end
