module Kobako
  module Transport
    class Run < Data
      NAME_PATTERN: Regexp

      attr_reader entrypoint: Symbol
      attr_reader args: Array[untyped]
      attr_reader kwargs: Hash[Symbol, untyped]

      def self.new: (entrypoint: Symbol | String, ?args: Array[untyped], ?kwargs: Hash[untyped, untyped]) -> Run

      def initialize: (entrypoint: Symbol | String, ?args: Array[untyped], ?kwargs: Hash[untyped, untyped]) -> void

      def encode: (Kobako::Catalog::Handles handler) -> String

      private

      def normalize_entrypoint: (Symbol | String target) -> Symbol

      def validate_args!: (Array[untyped] args) -> void

      def validate_kwargs!: (Hash[untyped, untyped] kwargs) -> void

      def forged_handle_message: (String slot) -> String
    end
  end
end
