module Kobako
  module Transport
    TAG_OK: Integer
    TAG_BREAK: Integer
    TAG_RESERVED: Integer
    TAG_ERROR: Integer
    LIVE_TAGS: Array[Integer]

    class Yield
      attr_reader tag: Integer
      attr_reader value: Kobako::Codec::wire_value | Kobako::Fault

      def self.decode: (String bytes) -> Yield

      def self.reject_dead_tag!: (Integer tag) -> void

      def initialize: (tag: Integer, value: untyped) -> void

      def with: (?tag: Integer, ?value: untyped) -> Yield

      def ok?: () -> bool

      def break?: () -> bool

      def error?: () -> bool

      def encode: () -> String

      def ==: (untyped other) -> bool

      def hash: () -> Integer
    end
  end
end
