module Kobako
  module Transport
    module YieldProxy
      def self?.build: (Kobako::Transport::Channel channel, Symbol break_tag) -> [Proc, Proc]

      def self?.yield_failure: (untyped payload, default: String) -> RuntimeError
    end
  end
end
