module Kobako
  module Transport
    class Yielder
      @yield_to_guest: ^(String) -> String
      @break_tag: Symbol
      @active: bool

      def initialize: (^(String) -> String yield_to_guest, Symbol break_tag) -> void

      def yield: (*untyped args) -> untyped

      def to_proc: () -> Proc

      def invalidate!: () -> void

      private

      def yield_failure: (untyped payload, default: String) -> RuntimeError
    end
  end
end
