module Kobako
  module Transport
    class Yielder
      @yield_to_guest: Kobako::Transport::_GuestYielder
      @break_tag: Symbol
      @handler: Kobako::Codec::_HandleTable
      @active: bool

      def initialize: (Kobako::Transport::_GuestYielder yield_to_guest, Symbol break_tag, Kobako::Codec::_HandleTable handler) -> void

      def yield: (*untyped args) -> untyped

      def to_proc: () -> Proc

      def invalidate!: () -> void

      private

      def restore: (untyped value) -> untyped

      def yield_failure: (untyped payload, default: String) -> RuntimeError
    end
  end
end
