// build.rs — kobako-wasm Ruby boot bytecode pipeline.
//
// Purpose
// -------
// On the production target (wasm32-wasip1), precompile `mrblib/*.rb`
// to RITE-format `.mrb` blobs that `src/kobako/bytecode.rs` embeds via
// `include_bytes!`. These blobs carry the kobako-specific Ruby surface
// (top-level `::IO` instance methods, Kernel delegators routing
// through assignable `$stdout` / `$stderr`) so the Guest Binary boots
// with `puts` / `print` / `p` already wired up.
//
// Why this lives in `kobako-wasm` and not `kobako-mruby-sys`
// ----------------------------------------------------------
// The Ruby files under `mrblib/` are kobako's own boot code, not
// part of the mruby C runtime. Their RITE output is consumed by
// `kobako-wasm`'s `src/kobako/bytecode.rs` via `include_bytes!`, so
// the bytecode pipeline naturally tracks the consumer crate. The
// mruby C API FFI surface (the `extern "C"` declarations and the
// layout-safe C shims) is a separate concern handled in the sibling
// `kobako-mruby-sys` crate's own `build.rs`.
//
// What this file does NOT do
// --------------------------
//   * It does not link `libmruby.a` or compile any C shim. Those
//     responsibilities sit in `kobako-mruby-sys/build.rs`; this crate
//     pulls them in transitively through the `kobako-mruby-sys` path
//     dependency.
//   * It does not run `bindgen`. The mruby C API binding referenced
//     by call sites is generated by `kobako-mruby-sys`'s own `build.rs`
//     and re-exported through `crate::mruby::sys`.
//
// Contract with the Rake driver
// -----------------------------
// The Rake driver exports `MRBC_PATH` before invoking cargo:
//
//   * `MRBC_PATH` — absolute path to the host-target `mrbc` binary
//     produced by Stage B (`MRuby::Build.new("host")` in
//     `build_config/wasi.rb`). When unset, this script falls back to
//     the well-known `vendor/mruby/build/host/bin/mrbc` location.
//
// Idempotency
// -----------
// Cargo only re-runs this script when its source changes or when one
// of the `cargo:rerun-if-env-changed=` / `cargo:rerun-if-changed=`
// entries below changes.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    // Always re-run when the build-script-relevant env vars change.
    // Without these, cargo's default behavior is to re-run only when
    // build.rs itself is touched, which would mask MRBC_PATH rebinding
    // between invocations.
    println!("cargo:rerun-if-env-changed=MRBC_PATH");
    println!("cargo:rerun-if-changed=build.rs");

    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();

    // Host target builds (used for `cargo test` running the codec /
    // envelope unit tests on the developer's machine) do not embed the
    // boot bytecode — the host-target rlib never reaches the
    // `include_bytes!` call sites. Bail out without producing the
    // placeholder blobs to keep the host build path noise-free.
    if target_arch != "wasm32" {
        return;
    }

    // Stage C.5: precompile mrblib/*.rb to RITE-format .mrb blobs that
    // src/kobako/bytecode.rs embeds via `include_bytes!`. The host
    // `mrbc` emerges from the same vendored mruby tree as
    // `libmruby.a` (Stage B builds both); the path is either supplied
    // explicitly by the Rake driver via `MRBC_PATH` or auto-discovered
    // from CARGO_MANIFEST_DIR. When mrbc is unavailable (clean
    // checkout doing `cargo check` before `rake mruby:build`), we
    // drop empty placeholder files so the `include_bytes!` call sites
    // compile; the resulting cdylib would fail at runtime, but at
    // that point `wasm:build` would also have failed for the missing
    // libmruby.a anyway, so the degradation is self-consistent.
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    precompile_mrblib(&manifest_dir, &out_dir);
}

/// Compile every `mrblib/*.rb` source into a matching `OUT_DIR/<stem>.mrb`
/// RITE blob. `src/kobako/bytecode.rs` `include_bytes!` reads those blobs
/// into compile-time `&[u8]` constants. Resolves `mrbc` from the
/// `MRBC_PATH` env var (set by `tasks/wasm.rake`) first, falling back to
/// the vendored host-target build that Stage B produces at a known
/// project-relative path. When neither resolves, emits empty placeholder
/// blobs so the `include_bytes!` call sites still type-check during a
/// `cargo check` against a clean checkout — the same lane that already
/// tolerates a missing `libmruby.a` for link-time wiring above.
fn precompile_mrblib(manifest_dir: &Path, out_dir: &Path) {
    let mrblib_dir = manifest_dir.join("mrblib");
    let sources = ["io.rb", "kernel.rb"];

    for src in &sources {
        let src_path = mrblib_dir.join(src);
        println!("cargo:rerun-if-changed={}", src_path.display());
    }

    let mrbc = resolve_mrbc(manifest_dir);

    for src in &sources {
        let src_path = mrblib_dir.join(src);
        let stem = src.strip_suffix(".rb").unwrap();
        let dst_path = out_dir.join(format!("{}.mrb", stem));

        if let Some(ref mrbc_bin) = mrbc {
            let status = Command::new(mrbc_bin)
                .arg("-o")
                .arg(&dst_path)
                .arg(&src_path)
                .status()
                .unwrap_or_else(|e| panic!("failed to spawn {}: {}", mrbc_bin.display(), e));
            if !status.success() {
                panic!(
                    "mrbc {} -> {} failed with status {}",
                    src_path.display(),
                    dst_path.display(),
                    status
                );
            }
        } else {
            // No mrbc available — write an empty placeholder so
            // include_bytes! compiles. cargo:warning surfaces the
            // degraded build to the operator.
            fs::write(&dst_path, b"")
                .unwrap_or_else(|e| panic!("write placeholder {}: {}", dst_path.display(), e));
            println!(
                "cargo:warning=mrbc not found; wrote empty {} (run `rake mruby:build`)",
                dst_path.display()
            );
        }
    }
}

/// Locate the host-target `mrbc` binary. Preference order:
///
///   1. `MRBC_PATH` env var (set by `tasks/wasm.rake` cargo_build_env).
///   2. `<crate>/../../vendor/mruby/build/host/bin/mrbc` — the path
///      where `MRuby::Build.new("host")` in `build_config/wasi.rb`
///      drops the binary after `rake mruby:build`.
///
/// Returns `None` when neither resolves to an existing file, so the
/// caller can fall back to writing empty placeholder blobs.
fn resolve_mrbc(manifest_dir: &Path) -> Option<PathBuf> {
    if let Ok(path) = env::var("MRBC_PATH") {
        if !path.is_empty() {
            let candidate = PathBuf::from(path);
            if candidate.exists() {
                return Some(candidate);
            }
        }
    }

    let fallback = manifest_dir
        .join("..")
        .join("..")
        .join("vendor")
        .join("mruby")
        .join("build")
        .join("host")
        .join("bin")
        .join("mrbc");
    if fallback.exists() {
        Some(fallback)
    } else {
        None
    }
}
