module Kobako
  module RPC
    class Channel
      def initialize: (
        server: Kobako::Catalog::Binding,
        instance: untyped,
        handler: Kobako::Catalog::Handler
      ) -> void

      def dispatch: (String request_bytes) -> String

      def yield_to_block: (String args_bytes) -> String
    end
  end
end
