module Kobako
  module RPC
    module Dispatcher
      class UndefinedTargetError < StandardError
      end

      class DisconnectedTargetError < StandardError
      end

      def self?.dispatch: (String request_bytes, Server server) -> String

      def self?.encode_dispatch_error: (StandardError error) -> String

      def self?.perform_dispatch: (String request_bytes, Server server) -> untyped

      def self?.invoke: (untyped target, String method, Array[untyped] args, Hash[Symbol, untyped] kwargs) -> untyped

      def self?.resolve_arg: (untyped value, HandleTable handle_table) -> untyped

      def self?.resolve_target: (String | Kobako::RPC::Handle target, Server server, HandleTable handle_table) -> untyped

      def self?.resolve_path: (String path, Server server) -> untyped

      def self?.resolve_handle: (Kobako::RPC::Handle handle, HandleTable handle_table) -> untyped

      def self?.fetch_live_object: (Integer id, HandleTable handle_table) -> untyped

      def self?.encode_ok: (untyped value, Server server) -> String

      def self?.wrap_as_handle: (untyped value, Server server) -> Kobako::RPC::Handle

      def self?.encode_error: (String type, String message) -> String
    end
  end
end
