module Kobako
  module Catalog
    class Extensions
      def initialize: () -> void

      def install: (untyped extension, snippets: Kobako::Catalog::Snippets, services: Kobako::Catalog::Services) -> self

      def seal!: () -> self

      def resolve: () -> Hash[String, untyped]

      private

      def install_object: (untyped backend) -> untyped

      def resolve_backend: (untyped extension, Hash[String, untyped] resolved, Hash[untyped, untyped] by_provider) -> void

      def validate!: (untyped extension) -> void

      def assert_dependencies!: () -> void

      def symbolize: (untyped name) -> untyped
    end
  end
end
