module Kobako
  module Catalog
    class Namespaces
      def initialize: (?handler: Kobako::Catalog::Handles) -> void

      def define: (Symbol | String name) -> Kobako::Namespace

      def lookup: (String target) -> untyped

      def encode: () -> String

      def seal!: () -> self

      def sealed?: () -> bool
    end
  end
end
