module Kobako
  module Catalog
    class Services
      NAME_PATTERN: Regexp

      def initialize: (?handler: Kobako::Catalog::Handles) -> void

      def bind: (Symbol | String path, untyped object) -> self

      def lookup: (Symbol | String target) -> untyped

      def refresh: (Symbol | String path, untyped object) -> self

      def encode: () -> String

      def seal!: () -> self

      def sealed?: () -> bool

      private

      def validate_path!: (Symbol | String path) -> String

      def collision?: (String path) -> bool
    end
  end
end
