module Kobako
  module Catalog
    class Snippets
      NAME_PATTERN: Regexp

      type entry = Kobako::Snippet::Source | Kobako::Snippet::Binary

      type tuple = [Symbol, String?, String]

      def initialize: () -> void

      def register: (?code: String?, ?name: (Symbol | String)?, ?binary: String?) -> (Symbol | nil)

      def entries: () -> Array[tuple]

      private

      def register_source!: (String? code, (Symbol | String)? name) -> Symbol

      def ensure_source_args!: (String? code, (Symbol | String)? name) -> [String, Symbol | String]

      def register_binary!: (String bytes) -> nil

      def entry_tuple: (entry) -> tuple

      def normalize_name: (Symbol | String name) -> Symbol
    end
  end
end
