module Kobako
  module Snippet
    class Binary < Data
      KIND: String

      attr_reader body: String

      def self.new: (body: String) -> Binary
                  | (String body) -> Binary
    end
  end
end
