module Kobako
  module Snippet
    class Table
      NAME_PATTERN: Regexp

      type entry = Kobako::Snippet::Source | Kobako::Snippet::Binary

      def initialize: () -> void

      def register: (String code, Symbol | String name) -> Symbol

      def register_binary: (String bytes) -> nil

      def encode: () -> String

      def each: () { (entry) -> void } -> Array[entry]
              | () -> Enumerator[entry, Array[entry]]

      def names: () -> Array[Symbol]

      def size: () -> Integer

      def empty?: () -> bool

      private

      def entry_payload: (entry) -> Hash[String, untyped]

      def normalize_name: (Symbol | String name) -> Symbol
    end
  end
end
