module Kobako
  class Error < StandardError
  end

  module CarriesExecution
    attr_reader execution: Kobako::Execution?

    def with_execution: (Kobako::Execution execution) -> self
  end

  class TrapError < Error
    include CarriesExecution
  end

  class TimeoutError < TrapError
  end

  class MemoryLimitError < TrapError
  end

  class SetupError < Error
  end

  class ModuleNotBuiltError < SetupError
  end

  module Diagnosable : Error
    attr_reader origin: String?
    attr_reader klass: String?
    attr_reader backtrace_lines: Array[String]?

    def initialize: (
      String message,
      ?origin: String?,
      ?klass: String?,
      ?backtrace_lines: Array[String]?
    ) -> void
  end

  class SandboxError < Error
    include Diagnosable
    include CarriesExecution
  end

  class ServiceError < Error
    include Diagnosable
    include CarriesExecution
  end

  class NoServiceError < ServiceError
  end

  class ServiceArgumentError < ServiceError
  end

  class HandleExhaustedError < SandboxError
  end

  class BytecodeError < SandboxError
  end

  class UndefinedEntrypointError < SandboxError
    attr_reader name: Symbol?
    attr_reader available: Array[Symbol]

    def initialize: (
      String message,
      ?name: Symbol?,
      ?available: Array[Symbol],
      ?origin: String?,
      ?klass: String?,
      ?backtrace_lines: Array[String]?
    ) -> void
  end

  class PoolTimeoutError < Error
  end
end
