module Kobako
  class Error < StandardError
  end

  class TrapError < Error
  end

  class TimeoutError < TrapError
  end

  class MemoryLimitError < TrapError
  end

  class SandboxError < Error
    attr_reader origin: String?
    attr_reader klass: String?
    attr_reader backtrace_lines: Array[String]?
    attr_reader details: untyped

    def initialize: (
      String message,
      ?origin: String?,
      ?klass: String?,
      ?backtrace_lines: Array[String]?,
      ?details: untyped
    ) -> void
  end

  class ServiceError < Error
    attr_reader origin: String?
    attr_reader klass: String?
    attr_reader backtrace_lines: Array[String]?
    attr_reader details: untyped

    def initialize: (
      String message,
      ?origin: String?,
      ?klass: String?,
      ?backtrace_lines: Array[String]?,
      ?details: untyped
    ) -> void

    class Disconnected < ServiceError
    end
  end

  class HandleTableError < SandboxError
  end

  class HandleTableExhausted < HandleTableError
  end
end
