module Kobako
  class Execution
    attr_reader value: untyped
    attr_reader usage: Kobako::Usage

    def initialize: (
      value: untyped,
      usage: Kobako::Usage,
      stdout: Kobako::Capture,
      stderr: Kobako::Capture,
      failed: bool
    ) -> void

    def failed?: () -> bool

    def stdout: () -> String

    def stderr: () -> String

    def stdout_truncated?: () -> bool

    def stderr_truncated?: () -> bool
  end
end
