module Kobako
  class Handle
    MIN_ID: Integer
    MAX_ID: Integer

    attr_reader id: Integer

    def initialize: (id: Integer) -> void

    def self.from_wire: (Integer id) -> Handle

    def with: (?id: Integer) -> Handle

    def ==: (untyped other) -> bool

    def hash: () -> Integer
  end
end
