module Kobako
  class Sandbox
    DEFAULT_OUTPUT_LIMIT: Integer

    DEFAULT_TIMEOUT_SECONDS: Float

    DEFAULT_MEMORY_LIMIT: Integer

    attr_reader wasm_path: String
    attr_reader instance: Kobako::Wasm::Instance
    attr_reader stdout_limit: Integer
    attr_reader stderr_limit: Integer
    attr_reader timeout: Float?
    attr_reader memory_limit: Integer?
    attr_reader services: Kobako::RPC::Server
    attr_reader snippets: Kobako::SnippetTable

    def initialize: (
      ?wasm_path: String?,
      ?stdout_limit: Integer?,
      ?stderr_limit: Integer?,
      ?timeout: (Float | Integer)?,
      ?memory_limit: Integer?
    ) -> void

    def stdout: () -> String

    def stderr: () -> String

    def stdout_truncated?: () -> bool

    def stderr_truncated?: () -> bool

    def define: (Symbol | String name) -> Kobako::RPC::Namespace

    def preload: (code: String, name: Symbol | String) -> Kobako::Sandbox

    def run: (Symbol | String target, *untyped args, **untyped kwargs) -> untyped

    def eval: (String code) -> untyped

    private

    def clear_captures!: () -> void

    def reset_invocation_state!: () -> void

    def read_captures!: () -> void

    def invoke!: (Symbol verb) { () -> void } -> untyped

    def raise_trap: (Symbol verb, Kobako::Wasm::Error err) -> bot

    def take_result!: () -> untyped
  end
end
