module Kobako
  class Snapshot
    def return_bytes: () -> String
    def stdout_bytes: () -> String
    def stdout_truncated: () -> bool
    def stderr_bytes: () -> String
    def stderr_truncated: () -> bool

    def stdout: () -> Kobako::Capture
    def stderr: () -> Kobako::Capture
  end
end
