module Kobako
  class SnippetTable
    NAME_PATTERN: Regexp

    SOURCE_KIND: String

    def initialize: () -> void

    def register: (String code, Symbol | String name) -> Symbol

    def encoded_frame3: () -> String

    def each: () { ([Symbol, String]) -> void } -> Hash[Symbol, String]
            | () -> Enumerator[[Symbol, String], Hash[Symbol, String]]

    def names: () -> Array[Symbol]

    def size: () -> Integer

    def empty?: () -> bool

    private

    def normalize_name: (Symbol | String name) -> Symbol
  end
end
