module Kobako
  module Wasm
    class Error < StandardError
    end

    class ModuleNotBuiltError < Error
    end

    def self.default_path: () -> String

    class Instance
      def self.from_path: (String path) -> Instance

      def registry=: (Kobako::Registry registry) -> void

      def run: (String preamble, String source) -> void

      def stdout: () -> String

      def stderr: () -> String

      def outcome!: () -> String
    end
  end
end
