module Kobako
  module Yield
    TAG_OK: Integer
    TAG_BREAK: Integer
    TAG_RESERVED: Integer
    TAG_ERROR: Integer
    LIVE_TAGS: Array[Integer]

    def self?.encode_response: (Response response) -> String

    def self?.decode_response: (String bytes) -> Response

    def self?.reject_dead_tag!: (Integer tag) -> void
  end
end
