#!/usr/bin/env ruby
# frozen_string_literal: true

# Drive a real DSL gem from inside the sandbox. The guest writes a
# line-message-builder Flex DSL (`Flex.with { bubble do ... end }`); the host
# owns the builder. Each guest call forwards onto the real
# Line::Message::Builder::Flex nodes across the wasm boundary, so the JSON
# printed here is genuine LINE Flex output — paste it into LINE's Flex
# Simulator to see it render.
#
# The DSL source is untrusted (imagine it generated by an AI). The sandbox
# confines it to the bound builder vocabulary and nothing else, which is the
# guarantee a plain Ruby `eval` cannot make — but the point of this example is
# simply that a real gem's DSL works inside that boundary, reading almost
# exactly as the gem's own `.with { ... }` entry does.
#
# Usage:
#   ruby examples/line-flex-message/app.rb --example default
#   ruby examples/line-flex-message/app.rb --example cards
#   ruby examples/line-flex-message/app.rb --example receipt
#
# From a clone of the kobako repository, prefix with `bundle exec` so the local
# checkout is used instead of the released gem.

require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "kobako", "~> 0.16.0"
  gem "line-message-builder", "~> 0.9"
end

require "kobako"
require "line/message/builder"
require "json"

# Example types are nested under LineFlex so the file carries a single
# top-level constant and reads top-down.
module LineFlex
  # The guest idiom, preloaded as the Extension's source. `Build` is a generic
  # wrapper — `method_missing` forwards each call onto the wrapped Handle and,
  # when a block is given, descends into the returned child node. `Flex.with`
  # mirrors line-message-builder's own `.with { }` entry: the block runs on a
  # root exposing `bubble` / `carousel`, and the assembled Flex JSON is
  # returned. No builder logic is reimplemented in the guest.
  GUEST_SOURCE = <<~MRUBY
    class Build
      def initialize(handle) = (@handle = handle)

      def method_missing(name, *args, **kwargs, &blk)
        result = @handle.public_send(name, *args, **kwargs)
        return result unless blk

        (result.is_a?(Kobako::Handle) ? Build.new(result) : result).instance_eval(&blk)
        self
      end

      def respond_to_missing?(_name, _include_private = false) = true

      def handle = @handle
    end

    module Flex
      def self.with(&blk)
        root = Root.new
        root.instance_eval(&blk)
        root.to_h
      end

      class Root
        def bubble(&blk)
          build(Studio.bubble, &blk)
        end

        def carousel(&blk)
          build(Studio.carousel, &blk)
        end

        def to_h = @node.handle.to_h

        private

        def build(handle, &blk)
          @node = Build.new(handle)
          @node.instance_eval(&blk) if blk
          @node
        end
      end
    end
  MRUBY

  # Host adapter over a line-message-builder node. The gem's box children
  # (`text`, `box`, `button`, ...) return the mutated `contents` Array rather
  # than the child they create, because ordinary usage nests inside a
  # construction-time block. Across the wasm boundary the guest holds that
  # block, so the adapter hands back the freshly created child node for the
  # guest to descend into; a non-node result passes straight through.
  #
  # Forwarding is gated on the node *defining* the method (`method_defined?`,
  # not `respond_to?`): line-message-builder's own nodes answer `respond_to?`
  # to everything through their context delegation, which would let the codec's
  # `to_msgpack` probe be swallowed and the node mis-encode as a wire value
  # instead of crossing to the guest as a Capability Handle. A real builder
  # method forwards; anything else raises, so the codec wraps the node.
  class Buildable
    def initialize(node) = (@node = node)

    def method_missing(name, *, **)
      return super unless @node.class.method_defined?(name)

      result = @node.public_send(name, *, **)
      child = result.is_a?(Array) ? result.last : result
      child.is_a?(Line::Message::Builder::Base) ? Buildable.new(child) : result
    end

    def respond_to_missing?(name, _include_private = false) = @node.class.method_defined?(name)

    def to_h = @node.to_h
  end

  # The backend bound at the guest constant `Studio`: it mints fresh root
  # builders. A bubble or carousel is a stateful node, so it crosses to the
  # guest as a Handle the guest's `Flex.with` facade descends into.
  class Studio
    def initialize = (@context = Line::Message::Builder::Context.new(nil))

    def bubble = Buildable.new(Line::Message::Builder::Flex::Bubble.new(context: @context))
    def carousel = Buildable.new(Line::Message::Builder::Flex::Carousel.new(context: @context))
  end

  # A host helper Service bound at the guest constant `Assets`. It mirrors the
  # line-message-builder view-context helper: the guest names an asset and the
  # host resolves it to a URL, so asset locations stay host-side instead of
  # being hard-coded into the untrusted script.
  class Assets
    def image_url(name) = "https://placehold.co/700x230/4B2E2B/FFFFFF/png?text=#{name}"
  end

  # A single Flex bubble — a simplified café card. It stays within the gem's
  # 0.9 surface: a bold title via `span`, baseline info rows, and buttons that
  # carry a `message` action.
  DEFAULT_SCRIPT = <<~MRUBY
    Flex.with do
      bubble do
        hero_image "https://developers-resource.landpress.line.me/fx/img/01_1_cafe.png",
                   size: :full, aspect_ratio: "20:13", aspect_mode: :cover
        body layout: :vertical, spacing: :md do
          text do
            span "Brown Cafe", weight: :bold, size: :xl
          end
          box layout: :baseline, spacing: :sm do
            text "Place", color: "#aaaaaa", size: :sm, flex: 1
            text "Flex Tower, 7-7-4 Midori-ku, Tokyo", wrap: true, color: "#666666", size: :sm, flex: 5
          end
          box layout: :baseline, spacing: :sm do
            text "Time", color: "#aaaaaa", size: :sm, flex: 1
            text "10:00 - 23:00", wrap: true, color: "#666666", size: :sm, flex: 5
          end
        end
        footer layout: :vertical, spacing: :sm do
          button style: :link, height: :sm do
            message "CALL", label: "CALL"
          end
          button style: :link, height: :sm do
            message "WEBSITE", label: "WEBSITE"
          end
        end
      end
    end
  MRUBY

  # A Flex carousel — a three-item coffee menu. The guest loops over a menu and
  # `bubble` appends a card per item; each card is an independent bubble dialect
  # the facade descends into.
  CARDS_SCRIPT = <<~'MRUBY'
    menu = [
      ["Espresso", "$3.50", "4B2E2B"],
      ["Latte", "$4.20", "8C6A4A"],
      ["Cappuccino", "$4.00", "A9744F"]
    ]

    Flex.with do
      carousel do
        menu.each do |name, price, tint|
          bubble do
            hero_image "https://placehold.co/600x400/#{tint}/FFFFFF/png?text=#{name}",
                       size: :full, aspect_ratio: "20:13", aspect_mode: :cover
            body layout: :vertical, spacing: :sm do
              text do
                span name, weight: :bold, size: :lg
              end
              text price, color: "#666666", size: :sm
            end
            footer do
              button style: :primary, height: :sm do
                message "Order #{name}", label: "Order"
              end
            end
          end
        end
      end
    end
  MRUBY

  # A receipt card assembled from host-injected data. The order — a customer
  # and a variable list of line items — is passed to `#run`, so one guest
  # template renders a different card for different data. `Assets.image_url`
  # resolves the banner host-side.
  RECEIPT_SOURCE = <<~'MRUBY'
    Receipt = lambda do |order|
      Flex.with do
        bubble do
          hero_image Assets.image_url("Receipt"), size: :full, aspect_ratio: "20:13", aspect_mode: :cover
          body layout: :vertical, spacing: :md do
            text do
              span "Thanks, #{order["customer"]}!", weight: :bold, size: :lg
            end
            box layout: :vertical, spacing: :sm, margin: :lg do
              order["items"].each do |item|
                box layout: :horizontal do
                  text item["name"], size: :sm, flex: 4
                  text item["price"], size: :sm, align: :end, flex: 2
                end
              end
            end
            box layout: :horizontal, margin: :md do
              text flex: 4 do
                span "Total", weight: :bold, size: :sm
              end
              text align: :end, flex: 2 do
                span order["total"], weight: :bold, size: :sm
              end
            end
          end
        end
      end
    end
  MRUBY

  # A sample order the host injects into the receipt template. Change it and the
  # same template renders a different card.
  ORDER = {
    "customer" => "Alice",
    "items" => [
      { "name" => "Espresso", "price" => "$3.50" },
      { "name" => "Croissant", "price" => "$2.80" },
      { "name" => "Cappuccino", "price" => "$4.00" }
    ],
    "total" => "$10.30"
  }.freeze

  # Composes the guest idiom (`Build` + the `Flex.with` facade) with the host
  # backend, bound at the guest constant `Studio`. The provider is callable, so
  # a fresh builder backs each invocation.
  def self.extension
    Kobako::Extension.new(
      name: :LineFlex,
      source: GUEST_SOURCE,
      backend: Kobako::Extension::Backend.new(path: "Studio", provider: -> { Studio.new })
    )
  end

  # Assemble the named example inside the sandbox and return its Flex JSON as a
  # Ruby Hash.
  def self.render(sandbox, name)
    case name
    when "default" then sandbox.eval(DEFAULT_SCRIPT)
    when "cards" then sandbox.eval(CARDS_SCRIPT)
    when "receipt" then render_receipt(sandbox)
    else raise ArgumentError, "unknown example: #{name.inspect}"
    end
  end

  # The receipt example binds the `Assets` helper, preloads the `Receipt`
  # template, and injects the order through `#run` — the host data path the
  # `#eval` examples do not exercise.
  def self.render_receipt(sandbox)
    sandbox.bind("Assets", Assets.new)
    sandbox.preload(code: RECEIPT_SOURCE, name: :Receipt)
    sandbox.run(:Receipt, ORDER)
  end
end

example = "default"
if (flag = ARGV.index("--example"))
  example = ARGV[flag + 1] or abort "usage: app.rb --example <name>"
end

sandbox = Kobako::Sandbox.new
sandbox.install(LineFlex.extension)
card =
  begin
    LineFlex.render(sandbox, example)
  rescue ArgumentError => e
    abort e.message
  end

# The banner goes to stderr so stdout is pure JSON — pipe it straight into
# pbcopy or the Flex Simulator.
warn "line-flex-message — a real DSL gem, driven from inside the sandbox"
warn "example: #{example}"
puts JSON.pretty_generate(card)
