module Kobako
  module Yield
    class Response
      attr_reader tag: Integer
      attr_reader value: untyped

      def initialize: (tag: Integer, value: untyped) -> void

      def with: (?tag: Integer, ?value: untyped) -> Response

      def ok?: () -> bool

      def break?: () -> bool

      def error?: () -> bool

      def ==: (untyped other) -> bool

      def hash: () -> Integer
    end
  end
end
